[workspace]
members = ["flotsync_core", "flotsync_messages", "flotsync_discovery", "flotsync_discovery_cli", "flotsync_data_types", "flotsync_utils"]
resolver = "3"

[workspace.dependencies]
snafu = "0.8"
itertools = "0.14"
