[package]
name = "flotsync_core"
version = "0.1.0"
edition = "2024"

[dependencies]
flotsync_utils = { path = "../flotsync_utils" }
itertools = "0.14"
regex = "1"
snafu = "0.8"
uuid = { version = "1", features = ["v4"] }
ahash = "0.8"

[dev-dependencies]
proptest = "1"
maplit = "1"
